---
# tasks file for nmap
- name: Update apt cache (for Debian-based systems)
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install nmap package
  become: yes
  package:
    name: nmap
    state: present
    
- name: Update yum cache (for Red Hat-based systems)
  become: yes
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'